#goal 
geometry_msgs/PoseStamped pose_goal
---
#result
bool result_state
string error_string
oea_msgs/Oea_path planned_path # carries path and zone tolerance information
---
#feedback
bool state
string description